### ISSUE TITLE
Version mismatch on NPM

### ISSUE THREAD

**Issue by dtothefp** [jonschlinkert/plasma#10]
why is `0.9.1` on NPM but in `master` here we have `0.9.0`. API has changed from `loader` to `dataLoader`, I'm confused :neckbeard:

**Comment by jonschlinkert** [comment]
looks like it just didn't get pushed up. it is now

**Comment by jonschlinkert** [comment]
fwiw, there was a period this past year where my internet connection was terrible. this happened a few times when I published to npm, lost the connection and had to wait for hours to get back online. sorry about that

**Comment by dtothefp** [comment]
No worries. Easy enough to look into node_modules. Just wanted to give you a heads up

**Comment by jonschlinkert** [comment]
ok, thanks for letting me know
