### ISSUE TITLE
use the `csv` (or `csv-parse`) NPM module instead

### ISSUE THREAD

**Issue by drewfish** [jonschlinkert/plasma#6]
Hi,

I noticed that you just added support for CSV files. Have you looked at the `csv` (or it's child, `csv-parse`) NPM package? There's a surprisingly large number of subtle differences in CSV files, and using an established package might save you some trouble.

Just an idea, I don't really have much invested in plasma support for CSV.

**Comment by jonschlinkert** [comment]
removing since direct support for csv was removed
